services:
    web:
        build: ./app
        restart: unless-stopped
        container_name: web
        ports:
            - "127.0.0.1:3000:3000"
        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - certs:/etc/nginx/certs:ro
            - ./app:/etc/app
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            - VIRTUAL_HOST=${HOST}
            - GOOGLE_APPLICATION_CREDENTIALS=./google-cloud.json
            - FIREBASE_API_KEY=AIzaSyCwBM6pEe6m09J8hLco4Dzsc_9bDkxrpwg
            - HOST=http://sorosbot.com
            - API_HOST=http://api.sorosbot.com
            - CODE_HOST=http://freqtrade.sorosbot.com
    api:
        build: ./api
        restart: unless-stopped
        container_name: api
        ports:
            - "127.0.0.1:5000:5000"
        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - certs:/etc/nginx/certs:ro
            - ./api:/etc/app
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            - VIRTUAL_HOST=api.${HOST}
            - GOOGLE_APPLICATION_CREDENTIALS=./google-cloud.json
            - FIREBASE_API_KEY=AIzaSyCwBM6pEe6m09J8hLco4Dzsc_9bDkxrpwg
    code-server:
        image: ghcr.io/linuxserver/code-server
        container_name: code-server
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
            - PROXY_DOMAIN=code.sorosbot.com #optional
            - VIRTUAL_HOST=code.${HOST}
        volumes:
            - ./dev/config:/config
        ports:
            - 127.0.0.1:8443:8443
        restart: unless-stopped
            
    freqtrade:
        image: freqtradeorg/freqtrade:stable
        # image: freqtradeorg/freqtrade:develop
        # Use plotting image
        # image: freqtradeorg/freqtrade:develop_plot
        # Build step - only needed when additional dependencies are needed
        # build:
        #   context: .
        #   dockerfile: "./docker/Dockerfile.custom"
        restart: unless-stopped
        container_name: freqtrade
        volumes:
            - conf:/etc/nginx/conf.d
            - vhost:/etc/nginx/vhost.d
            - certs:/etc/nginx/certs:ro
            - "./freqtrade/user_data:/freqtrade/user_data"
            - /var/run/docker.sock:/var/run/docker.sock:ro
        # Expose api on port 8080 (localhost only)
        # Please read the https://www.freqtrade.io/en/latest/rest-api/ documentation
        # before enabling this.
        ports:
            - 127.0.0.1:8080:8080
        # Default command used when running `docker compose up`
        command: >
            trade
            --logfile /freqtrade/user_data/logs/freqtrade.log
            --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
            --config /freqtrade/user_data/config.json
            --strategy SampleStrategy
        environment:
            - VIRTUAL_HOST=freqtrade.${HOST}

    nginx-proxy:
        image: nginx
        container_name: nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - conf:/etc/nginx/conf.d
            - html:/usr/share/nginx/html
            - certs:/etc/nginx/certs:ro
            - ./nginx/error.html:/var/www/default/error.html:ro
            - ./nginx/vhost.d:/etc/nginx/vhost.d
            - ./nginx/conf.d/server.conf:/etc/nginx/conf.d/server.conf:ro
            - ./nginx/include:/etc/nginx/include:ro
        restart: always
    
    docker-gen:
        image: jwilder/docker-gen
        command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        container_name: nginx-proxy-gen
        depends_on:
            - nginx-proxy
        volumes:
            - conf:/etc/nginx/conf.d
            - certs:/etc/nginx/certs:ro
            - ./nginx/vhost.d:/etc/nginx/vhost.d
            - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: always

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: nginx-proxy-le
        depends_on:
            - nginx-proxy
            - docker-gen
        volumes:
            - vhost:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - certs:/etc/nginx/certs
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            - NGINX_PROXY_CONTAINER=nginx-proxy
            - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy-gen
            - DEFAULT_EMAIL=ssl@sorosbot.com
        restart: always
    
volumes:
    conf:
    vhost: 
    html:
    certs:
    freqtrade:
    web:

networks:
    default:
        name: nginx-proxy