services:
  nginx-proxy:
    volumes:
      - ../nginx/certs:/etc/nginx/certs:ro
  docker-gen:
    volumes:
      - ../nginx/certs:/etc/nginx/certs:ro
  api:
    volumes:
      - ../nginx/certs:/etc/nginx/certs:ro
  web:
    volumes:
      - ../nginx/certs:/etc/nginx/certs:ro
      - ../app:/usr/src/app
      - ../app/build/assets/_app/assets/pages/__layout.svelte-a1f25787.css:/usr/src/app/build/layout.css:ro